#!/usr/bin/python3

JOBS = [
   "Plays golf.",
   "Goes scuba diving.",
   "Makes ice-sculptures.",
   "Drinks wine.",
   "Drives rally cars.",
   "Does bungee jumps.",
   "Collects beer mats.",
   "Likes stage-diving.",
   "Enjoys fart-surfing.",
   "Enjoys river-widening.",
   "Distills whisky.",
   "An expert at DIY.",
   "Enjoys French arthouse films.",
   "Plays Theme Park a lot.",
   "Has an HGV licence.",
   "Goes motorcycle racing.",
   "Plays classical violin and cello.",
   "Ardent train-wrecker.",
   "Dog-lover.",
   "Listens to the radio.",
   "Takes frequent baths.",
   "Raffia-work instructor.",
   "Hollows vegetables out to use as soap-holders.",
   "Part-time Special Constable.",
   "Ex-Quiz Show Host.",
   "Collects WW2 shrapnel.",
   "Rearranges furniture.",
   "Listens to rave and trip-hop music.",
   "Enrages insects with deodorant spray.",
   "Heckles poor comedians.",
   "Snoops for the council.",
   "Furtive gardener.",
   "Smuggles fake watches.",
   "Sings in a rock and roll band.",
   "Worships daytime television.",
   "Tickles trout.",
   "Baits tourists in museums.",
   "Very fast and diligent worker.",
   "Very conscientious. Cares deeply.",
   "Has wide range of skills.",
   "Very friendly and enjoys a laugh.",
   "Superb stamina. Just keeps going.",
   "Remarkably polite and genial manner.",
   "Incredibly talented and able.",
   "Cares a great deal about the job in hand.",
   "Is a perfectionist who just doesn't give up.",
   "Dedicated to helping people with a smile.",
   "Charming, polite and helpful.",
   "Generally well motivated and dedicated.",
   "Good-natured and very hard-working.",
   "Loyal and friendly.",
   "Careful and dependable in an emergency.",
   "Slow and fussy.",
   "Lazy and badly motivated.",
   "Poorly trained and feckless.",
   "Rude and abrasive. Gets people's backs up.",
   "Dreadful stamina - has a bad attitude.",
   "Deaf as a post. Smells faintly of cabbage.",
   "Rubbish at the job. A possible liability.",
   "Rash and easily distracted.",
   "Stressed and prone to mistakes.",
   "Twisted and resentful - burning up with hate.",
   "Careless and accident-prone.",
   "Not bothered about the job. Bone idle.",
   "Foolish risk-taker who couldn't care less.",
   "Sly, cunning and subversive.",
   "Arrogant and cocky.",
]

import random
print ' '.join(random.sample(JOBS, 2))
